### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by ymwdalex** [ing-bank/sparse_dot_topn#48]
Somehow some people meet this ValueError `numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`. This issue also happens in other python packages such hdbscan, top2vec. 

There are some ongoing discussions on this issue in hdbscan repository https://github.com/scikit-learn-contrib/hdbscan/issues/457. It seems that the problem is related to python, numpy, scipy and cython version. It seems that this problem is triggered by the latest version of numpy

**One workable solution is upgrading numpy to 1.20.0**

This issue is a reminder if sparse_dot_topn users meet the same question

**Comment by stephanecollot** [comment]
Hi just wanted to add, this is on going issue, that I faced with numpy this with version 1.21.1 (what I need to use)

One way that worked for me:

```
pip uninstall sparse_dot_topn
pip install sparse_dot_topn --no-cache-dir --no-binary :all: --no-build-isolation
```

**Comment by anton-ryzhov** [comment]
I also faced with the issue and found a root cause.

#### Minimal reproducible example
```shell
cd "$(mktemp -d)"
python -m venv .
bin/pip install numpy==1.21.0     # fails with this line, works fine without it
bin/pip install sparse-dot-topn==0.3.1
bin/python -c 'import sparse_dot_topn; print("Works fine")'
```

#### Explanation
As this package uses `cython` to compile binary library, and it depends on exact version of `numpy`, it's built every time from source on install — there is no binary distribution (`wheel`).

The package doesn’t require exact version of `numpy` to run but defines [a range](https://github.com/ing-bank/sparse_dot_topn/blob/09d1ec820eff81ab3e3223f11ef659d35f4e1acc/setup.py#L88). It also requires [the same range](https://github.com/ing-bank/sparse_dot_topn/blob/09d1ec820eff81ab3e3223f11ef659d35f4e1acc/setup.py#L81) at compiling time. And it works as expected only if both versions (on compile time and on runtime) were resolved equally. It could also work if versions are different but ABI is the same — but it’s not reliable and the issue could stay unnoticed next time.

`pip` compiles package on installation time in an isolated env. So it resolves `setup_requires`, installs such dependencies, compiles the binary, creates a wheel package. Then it resolves `install_requires`, installs packages if required and installs the package from just-created wheel into the original env.

The problem occurs when the env already have appropriate `numpy` — for example 1.21.0. That satisfies `install_requires numpy>=1.16.6`, so it is not reinstalled. But for compiling pip has installed `setup_requires numpy>=1.16.6`, which is 1.22.x [since December 31](https://pypi.org/project/numpy/1.22.0/). And apparently this version has incompatible ABI. 

The core problem that pip uses different versions on compile and runtime, but I don’t know if it’s possible to propagate the same version to compiling phase as it’s executed in an isolated env by design.

**Comment by gld3kk** [comment]
It seems this issue has come back - newest version of numpy leads to this issue as well as 1.20.0 mentioned earlier & --no-cache-dir --no-binary :all: --no-build-isolation.

What version of numpy and sparse_dot_topn (if any work)?

Or are there any other updated suggestions?

**Comment by ymwdalex** [comment]
@anton-ryzhov @gld3kk 

Thanks for your feedback and root cause analysis! We just released [v0.3.3](https://pypi.org/project/sparse-dot-topn/#files). There are two big improvements:
- we use `oldedst_support_numpy` and pyproject.toml to support NumPy forward compatible. So, `Expected 88 from C header, got 80 from PyObject` problem should be solved.
- We employed Github actions and CiBuildWheel, and make the wheels available for Py3.6-3.10 on multiple architectures of Linux, MacOS and Windows.

If you still have `Expected 88 from C header, got 80 from PyObject` or installation problems, please try the latest version.

If you find any problem with v0.3.3, please let us know. Thanks!

**Comment by ymwdalex** [comment]
[v0.3.3](https://pypi.org/project/sparse-dot-topn/#files) should fix this issue

**Comment by ywhcuhk** [comment]
the issue is still there with v0.3.3.  I am using Anaconda, with Numpy version 1.21.5

```
File ~/opt/anaconda3/lib/python3.9/site-packages/sparse_dot_topn_for_blocks/__init__.py:5, in <module>
      2 import sys
      4 if sys.version_info[0] >= 3:
----> 5     from sparse_dot_topn_for_blocks.awesome_cossim_topn import awesome_cossim_topn
      6 else:
      7     from awesome_cossim_topn import awesome_cossim_topn

File ~/opt/anaconda3/lib/python3.9/site-packages/sparse_dot_topn_for_blocks/awesome_cossim_topn.py:7, in <module>
      4 from scipy.sparse import isspmatrix_csr
      6 if sys.version_info[0] >= 3:
----> 7     from sparse_dot_topn_for_blocks import sparse_dot_topn as ct
      8     from sparse_dot_topn_for_blocks import sparse_dot_topn_threaded as ct_thread
      9 else:

File ~/opt/anaconda3/lib/python3.9/site-packages/sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:1, in init sparse_dot_topn_for_blocks.sparse_dot_topn()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by stephanecollot** [comment]
That is weird.
Could you give us your exact Python version? `python --version`
And the description of your environment: `pip list -v` and `conda list -v`
